version: '3.9'
services:
  backend: 
    build:
      context: ./backend
      dockerfile: go.Dockerfile 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./backend
    #       target: /app
    #       ignore:
    #         - tmp/
    #         - .dbdata/
    #     - action: rebuild
    #       path: go.mod
    #     - action: rebuild
    #       path: go.sum
    depends_on:
      - db

  db: 
    image: mysql:5.7.22
    restart: always 
    environment: 
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root 
      MYSQL_ROOT_PASSWORD: root 
    volumes: 
      - .dbdata:/var/lib/mysql
    

